= vue-chat-bot-task
:toc: preamble
:toc-title: Содержание

:note-caption: ℹ️

ifdef::env-github[]
:note-caption: :information_source:
endif::[]

Тестовое задание на вакансию Javascript frontend разработчик в ОптималСити.


== Демо

Github Pages: https://larento.github.io/vue-chat-bot-task


== Задание

[sidebar]
****
Необходимо написать приложение-чат бота. В основном окне должен быть расположен чат-виджет, где пользователь сможет набирать сообщение боту и получать от него ответы. При открытии окна бот должен поприветствовать пользователя, после чего вывести ему кнопки с вариантами продолжения дальнейшего общения. Например “Привет! Что я могу для Вас сделать?” и кнопки с вариантами “Заказать пиццу”, “Установить будильник”, “Вывести погоду”. При нажатии на кнопку реплика (со стороны пользователя) должна появиться в виджете так, как если бы пользователь набрал текст кнопки вручную. Бот должен ответить что то вроде “Хорошо, я закажу пиццу. Что еще могу сделать?”.

Как это примерно может выглядеть: https://lucasbassetti.com.br/react-simple-chatbot/#/

Бота нет необходимости делать сколь-либо интеллектуальным. Также нет необходимости использовать внешние сервисы или сетевые запросы. Весь интеллект бота можно захардкодить блоками if прямо в приложении.

Общение только текстом, без картинок, емодзи и т.п.

В задании, надо сконцентрироваться на визуальной части виджета, интерактивном процессе взаимодействия, кросс-браузерной верстке, удовлетворяющей современным требованиям (responsiveness итп). Необходимо использовать фреймворке Vue.js, можно использовать любые css фреймворк, UI kit, и любые другие внешние библиотеки.

Сделанное задание в собранном виде и рабочем состоянии необходимо выложить на любой бесплатный хостинг, такой как github.io, код разместить в репозитории, а нам прислать 2 ссылки.

Опциональной частью задания (и плюсом при устройстве на работу) будет описание вариантов как этот виджет можно встроить на сторонние сайты (как загрузить, как подсоединить к DOM на внешней странице ит.п.)
****


== Используемые технологии

* Vue.js
* Vuetify - библиотека компонентов для Vue.
* Sass
* Vite - сборщик / сервер для разработки.
* Bun - пакетный менеджер.


== Варианты встраивания окна с чат-ботом на внешний сайт

Есть несколько вариантов встраивания чат-бота на сайт, используя только DOM.


=== Через элемент `<iframe>`

Достаточно иметь API роут, на котором выводится HTML, содержащий окно с чатом. Этот URL указывается в атрибуте `src` в `<iframe>`.

.Преимущества:
* Достаточно добавить один элемент iframe, загружать необходимые для виджета CSS / JS ресурсы не требуется.
* Широко поддерживаются старыми версиями браузеров.

.Недостатки:
* Настройка обычно происходит с помощью query параметров в URL iframe.
* Тяжелее настраивать стили через CSS.
* Загрузка отдельного дерева HTML в iframe может занять больше времени, чем Shadow DOM, что плохо влияет на показатели Web Vitals.
* Могут быть проблемы с CORS.


=== С помощью Web Components
:ext-mdn-web-components: https://developer.mozilla.org/en-US/docs/Web/API/Web_components
:ext-vue-define-custom-element: https://vuejs.org/api/general.html#definecustomelement

Виджеты можно также подключать через {ext-mdn-web-components}[Web Components]. Для этого обычно подключается JavaScript модуль с определением компонента и файл со стилями. В HTML код страницы с виджетом добавляется веб-компонент с необходимыми атрибутами. Загруженный JS модуль определяет каким образом этот компонент следует добавить в DOM страницы.

.Преимущества:
* Компонент можно настраивать с помощью JS.
* Компонент может иметь кастомные атрибуты.
* Чуть проще добавлять стили для компонента - можно указывать inline стили; внутри Shadow DOM поддерживаются CSS Custom Properties.
* Vue.js 3 имеет {ext-vue-define-custom-element}[нативный метод] для создания Web Components.

.Недостатки:
* Web Components поддерживается только современными браузерами, поэтому может потребоваться polyfill.
* Нужно вручную подключать CSS / JS ресурсы.